#Q.1. convert 1D array to a 2D array with 2 rows

In [ ]:
import numpy as np

In [ ]:
# 1D array
np.arange(0,20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
# 2D array
data = np.arange(0,20).reshape(4,5)
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

#Q.2.Get the commen item between a and b

In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
c = []
for i in a:
 if i in b:
  if i not in c:
    c.append(i)
print(c)

np.array(c)


[2, 4]


array([2, 4])

In [ ]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

result = np.intersect1d(a,b)
result

array([2, 4])

#Q.3.Get all the items between 5 to 10 from a

In [ ]:
a = np.array([2, 6, 1, 9, 10, 3, 27])

for i in a:
  if i<=5 and i>=10:
    print(i)


In [ ]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
result = np.where(np.logical_and(a<=5,a>=10))
result

(array([], dtype=int64),)

#Q.4 Limit the number of items printed in python NumPy array a to a maximum of 6 elements.

In [ ]:
a = np.arange(10)
print(a)

b = np.clip(a,0,6)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 6 6 6]


# pandas

#1. Compute the minimum, 25th percentile, median, 75th, and maximum of ser

In [ ]:
import pandas as pd

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving imdb.csv to imdb.csv


In [ ]:
data = pd.read_csv("imdb.csv")

In [ ]:
data

star_rating                                            title  \
0            9.3                         The Shawshank Redemption   
1            9.2                                    The Godfather   
2            9.1                           The Godfather: Part II   
3            9.0                                  The Dark Knight   
4            8.9                                     Pulp Fiction   
..           ...                                              ...   
974          7.4                                          Tootsie   
975          7.4                      Back to the Future Part III   
976          7.4  Master and Commander: The Far Side of the World   
977          7.4                                      Poltergeist   
978          7.4                                      Wall Street   

    content_rating      genre  duration  \
0                R      Crime       142   
1                R      Crime       175   
2                R      Crime       200   
3            PG-13     Action       152   
4                R      Crime       154   
..             ...        ...       ...   
974             PG     Comedy       116   
975             PG  Adventure       118   
976          PG-13     Action       138   
977             PG     Horror       114   
978              R      Crime       126   

                                           actors_list  
0    [u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt...  
1      [u'Marlon Brando', u'Al Pacino', u'James Caan']  
2    [u'Al Pacino', u'Robert De Niro', u'Robert Duv...  
3    [u'Christian Bale', u'Heath Ledger', u'Aaron E...  
4    [u'John Travolta', u'Uma Thurman', u'Samuel L....  
..                                                 ...  
974  [u'Dustin Hoffman', u'Jessica Lange', u'Teri G...  
975  [u'Michael J. Fox', u'Christopher Lloyd', u'Ma...  
976  [u'Russell Crowe', u'Paul Bettany', u'Billy Bo...  
977  [u'JoBeth Williams', u"Heather O'Rourke", u'Cr...  
978  [u'Charlie Sheen', u'Michael Douglas', u'Tamar...  

[979 rows x 6 columns]

In [ ]:
data.describe()

star_rating    duration
count   979.000000  979.000000
mean      7.889785  120.979571
std       0.336069   26.218010
min       7.400000   64.000000
25%       7.600000  102.000000
50%       7.800000  117.000000
75%       8.100000  134.000000
max       9.300000  242.000000

#2. Creating A Pandas Data Frame and Using Sample Data Sets

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving Products.csv to Products.csv


In [ ]:
pd.read_csv("Products.csv")

ProductKey  ProductSubcategoryKey  ProductSKU              ProductName  \
0           214                     31   HL-U509-R    Sport-100 Helmet, Red   
1           215                     31     HL-U509  Sport-100 Helmet, Black   
2           218                     23   SO-B909-M   Mountain Bike Socks, M   
3           219                     23   SO-B909-L   Mountain Bike Socks, L   
4           220                     31   HL-U509-B   Sport-100 Helmet, Blue   
..          ...                    ...         ...                      ...   
288         602                      5     BB-8107        ML Bottom Bracket   
289         603                      5     BB-9108        HL Bottom Bracket   
290         604                      2  BK-R19B-44       Road-750 Black, 44   
291         605                      2  BK-R19B-48       Road-750 Black, 48   
292         606                      2  BK-R19B-52       Road-750 Black, 52   

               ModelName                                 ProductDescription  \
0              Sport-100  Universal fit, well-vented, lightweight , snap...   
1              Sport-100  Universal fit, well-vented, lightweight , snap...   
2    Mountain Bike Socks  Combination of natural and synthetic fibers st...   
3    Mountain Bike Socks  Combination of natural and synthetic fibers st...   
4              Sport-100  Universal fit, well-vented, lightweight , snap...   
..                   ...                                                ...   
288    ML Bottom Bracket       Aluminum alloy cups; large diameter spindle.   
289    HL Bottom Bracket             Aluminum alloy cups and a hollow axle.   
290             Road-750  Entry level adult bike; offers a comfortable r...   
291             Road-750  Entry level adult bike; offers a comfortable r...   
292             Road-750  Entry level adult bike; offers a comfortable r...   

    ProductColor ProductSize ProductStyle  ProductCost  ProductPrice  
0            Red           0            0      13.0863       34.9900  
1          Black           0            0      12.0278       33.6442  
2          White           M            U       3.3963        9.5000  
3          White           L            U       3.3963        9.5000  
4           Blue           0            0      12.0278       33.6442  
..           ...         ...          ...          ...           ...  
288          NaN           0            0      44.9506      101.2400  
289          NaN           0            0      53.9416      121.4900  
290        Black          44            U     343.6496      539.9900  
291        Black          48            U     343.6496      539.9900  
292        Black          52            U     343.6496      539.9900  

[293 rows x 11 columns]

# 3. Using NumPy, create a Pandas Data Frame with five rows and three columns.


In [ ]:
pd.DataFrame(np.arange(15).reshape(5,3))

0   1   2
0   0   1   2
1   3   4   5
2   6   7   8
3   9  10  11
4  12  13  14

# 4. For a Pandas Data Frame created from a NumPy array, what is the default behavior for the labels for the columns? For the rows?

In [ ]:
numpyarray = np.array([[15,20,25],
                      [34,11,20]])

pd.DataFrame(data = numpyarray,index = ['Row_1','Row_2'],columns = ['Col_1','Col_2','Col_3'])

Col_1  Col_2  Col_3
Row_1     15     20     25
Row_2     34     11     20

# 5. take csv file contains at least 10,000 rows and 12 columns which numerical and text values according to that continue following steps.


In [ ]:
from google.colab import files
uploaded = files.upload()

Saving googleplaystore.csv to googleplaystore.csv


In [ ]:
data = pd.read_csv("googleplaystore.csv")
data

App             Category  \
0         Photo Editor & Candy Camera & Grid & ScrapBook       ART_AND_DESIGN   
1                                    Coloring book moana       ART_AND_DESIGN   
2      U Launcher Lite – FREE Live Cool Themes, Hide ...       ART_AND_DESIGN   
3                                  Sketch - Draw & Paint       ART_AND_DESIGN   
4                  Pixel Draw - Number Art Coloring Book       ART_AND_DESIGN   
...                                                  ...                  ...   
10836                                   Sya9a Maroc - FR               FAMILY   
10837                   Fr. Mike Schmitz Audio Teachings               FAMILY   
10838                             Parkinson Exercices FR              MEDICAL   
10839                      The SCP Foundation DB fr nn5n  BOOKS_AND_REFERENCE   
10840      iHoroscope - 2018 Daily Horoscope & Astrology            LIFESTYLE   

       Rating Reviews                Size     Installs  Type Price  \
0         4.1     159                 19M      10,000+  Free     0   
1         3.9     967                 14M     500,000+  Free     0   
2         4.7   87510                8.7M   5,000,000+  Free     0   
3         4.5  215644                 25M  50,000,000+  Free     0   
4         4.3     967                2.8M     100,000+  Free     0   
...       ...     ...                 ...          ...   ...   ...   
10836     4.5      38                 53M       5,000+  Free     0   
10837     5.0       4                3.6M         100+  Free     0   
10838     NaN       3                9.5M       1,000+  Free     0   
10839     4.5     114  Varies with device       1,000+  Free     0   
10840     4.5  398307                 19M  10,000,000+  Free     0   

      Content Rating                     Genres      Last Updated  \
0           Everyone               Art & Design   January 7, 2018   
1           Everyone  Art & Design;Pretend Play  January 15, 2018   
2           Everyone               Art & Design    August 1, 2018   
3               Teen               Art & Design      June 8, 2018   
4           Everyone    Art & Design;Creativity     June 20, 2018   
...              ...                        ...               ...   
10836       Everyone                  Education     July 25, 2017   
10837       Everyone                  Education      July 6, 2018   
10838       Everyone                    Medical  January 20, 2017   
10839     Mature 17+          Books & Reference  January 19, 2015   
10840       Everyone                  Lifestyle     July 25, 2018   

              Current Ver         Android Ver  
0                   1.0.0        4.0.3 and up  
1                   2.0.0        4.0.3 and up  
2                   1.2.4        4.0.3 and up  
3      Varies with device          4.2 and up  
4                     1.1          4.4 and up  
...                   ...                 ...  
10836                1.48          4.1 and up  
10837                 1.0          4.1 and up  
10838                 1.0          2.2 and up  
10839  Varies with device  Varies with device  
10840  Varies with device  Varies with device  

[10841 rows x 13 columns]

# 6. Write the code to show the number of rows and columns in data frame.


In [ ]:
data.shape

(10841, 13)

# 7. How might you show the first few rows of data frame

In [ ]:
data.head(5)

App        Category  Rating  \
0     Photo Editor & Candy Camera & Grid & ScrapBook  ART_AND_DESIGN     4.1   
1                                Coloring book moana  ART_AND_DESIGN     3.9   
2  U Launcher Lite – FREE Live Cool Themes, Hide ...  ART_AND_DESIGN     4.7   
3                              Sketch - Draw & Paint  ART_AND_DESIGN     4.5   
4              Pixel Draw - Number Art Coloring Book  ART_AND_DESIGN     4.3   

  Reviews  Size     Installs  Type Price Content Rating  \
0     159   19M      10,000+  Free     0       Everyone   
1     967   14M     500,000+  Free     0       Everyone   
2   87510  8.7M   5,000,000+  Free     0       Everyone   
3  215644   25M  50,000,000+  Free     0           Teen   
4     967  2.8M     100,000+  Free     0       Everyone   

                      Genres      Last Updated         Current Ver  \
0               Art & Design   January 7, 2018               1.0.0   
1  Art & Design;Pretend Play  January 15, 2018               2.0.0   
2               Art & Design    August 1, 2018               1.2.4   
3               Art & Design      June 8, 2018  Varies with device   
4    Art & Design;Creativity     June 20, 2018                 1.1   

    Android Ver  
0  4.0.3 and up  
1  4.0.3 and up  
2  4.0.3 and up  
3    4.2 and up  
4    4.4 and up

#8. If you select a single column from the diamonds Data Frame, what will be the type of the return value?

In [ ]:
data[['App']]

App
0         Photo Editor & Candy Camera & Grid & ScrapBook
1                                    Coloring book moana
2      U Launcher Lite – FREE Live Cool Themes, Hide ...
3                                  Sketch - Draw & Paint
4                  Pixel Draw - Number Art Coloring Book
...                                                  ...
10836                                   Sya9a Maroc - FR
10837                   Fr. Mike Schmitz Audio Teachings
10838                             Parkinson Exercices FR
10839                      The SCP Foundation DB fr nn5n
10840      iHoroscope - 2018 Daily Horoscope & Astrology

[10841 rows x 1 columns]

In [ ]:
data.dtypes

App                object
Category           object
Rating            float64
Reviews            object
Size               object
Installs           object
Type               object
Price              object
Content Rating     object
Genres             object
Last Updated       object
Current Ver        object
Android Ver        object
dtype: object

In [ ]:
data[['App']].dtypes

App    object
dtype: object

#9. Create a line plot using the x and y values provided below. Label the y-axis as “Y” and
label the x-axis as “X”.
x = [3, 4, 5, 6]
y = [1.5, 2, 2.5, 3]

In [ ]:
import plotly.express as px

In [ ]:
x = [3,4,5,6]
y = [1.5,2,2.5,3]
px.line(x=x,y=y)

#10.Create an array of numbers between 0 and 6 with increments of 0.3 and name its “x”.Then on the same plot, plot x, x², x³, and x⁴. For consistency, use the following style linesrespectively, “ro”, “bs”, “g”, and “:”. Lastly, make sure that the x-axis covers 0 to 6, whilethe y-axis spans from 0 to 125. Do not worry if you are not familiar with the style lines —you will recognize them as soon as you see the plot.

 11. Heights and initials of a group of individuals are provided below. Create a bar plot titled
“Height Comparison” to compare the heights among this group.
height = [179, 155, 191, 152, 188, 177]
names = ['QA', 'WB', 'EC', 'RD', 'TE', 'YF']

In [ ]:
import pandas as pd

In [ ]:
import plotly.express as px

In [ ]:
height = [179, 155, 191, 152, 188, 177]
names = ['QA', 'WB', 'EC', 'RD', 'TE', 'YF']
px.bar(x = height,y = names,title = 'Height Comparison',orientation='v')




#12. Plot a histogram of x, where x consists of 100,000 randomly-selected points with a normal
distribution (hint: you can use numpy.random.randn() to generate the random points). The
histogram should have 10 bins. Look at how the histogram changes when we try 20 and 50
bins.

In [ ]:
import numpy as np

In [ ]:
F = np.arange(10000).reshape(1000,10)

In [ ]:
import plotly.graph_objects as go
import numpy as np
x = np.random.randn(500)
fig = go.Figure(data=[go.Histogram(x=x)])
fig.show()



#13. What are the features of TensorFlow?


1. Open-source Library
It is an open-source library that allows rapid and easier calculations in machine learning. It eases the switching of algorithms from one tool to another TensorFlow tool.

With the help of python, it provides the front-end API for the development of various machines and deep learning algorithms.

2. Easy to run
We can execute TensorFlow applications on various platforms such as Android, Cloud, IOS and various architectures such as CPUs and GPUs. This allows it to be executed on various embedded platforms.

TensorFlow has its own designed hardware to train the neural models known as Cloud TPUs (TensorFlow Processing unit).

3. Fast Debugging
It allows you to reflect each node, i.e., operation individually concerning its evaluation. Tensor Board works with the graph to visualize its working using its dashboard. It provides computational graphing methods that support an easy to execute paradigm.

4. Effective
It works with multi-dimensional arrays with the help of data structure tensor which represents the edges in the flow graph. Tensor identifies each structure using three criteria: rank, type, shape.

5. Scalable
It provides room for prediction of stocks, products, etc with the help of training using the same models and different data sets. It also allows for synchronous and asynchronous learning techniques and data ingestion. The graphical approach secures the distributed execution parallelism.

6. Easy Experimentation
TensorFlow transforms the raw data to the estimators-a form of data neural networks understand. TensorFlow feature columns allow the bridge between raw data and estimators to train the model. This adds the agility to the model for fast developmental insights.

7. Abstraction
TensorFlow provides a defined level of abstraction by reducing the code length and cutting the development time. The user needs to focus on logic disregarding the proper way of providing input to functions. A user can choose the model apt according to the system’s requirement.

8. Flexibility
TensorFlow provides the process of resolving complex topologies with the support of Keras API and data input pipelines. Keras provides easy prototyping and suits best for object-oriented neural networks.

TensorFlow eases the mechanism of machine learning with the assistance of such characteristics. It allows the user to create and manipulate the system to create different types of real-time models.

#14. List a few limitations of TensorFlow.


Advantages
1. Scalable
Tensorflow is not limited to one specific device. It works as efficiently on a cellular device as it works on any other complex machine. The library is so defined that its deployment isn’t limited to any one specific device.

2. Open Source Platform
It is available free of cost to anyone who wants to work with this. This feature makes it possible for any user to employ this module whenever and wherever required.
3. Graphs
Tensorflow has a better data visualization power than any other available library. This makes it working on neural networks easier.

4. Debugging
Tensorflow has Tensorboard which allows easy debugging of nodes. This helps reduce the overhead of visiting the whole code.

5. Parallelism
TensorFlow employs GPU and CPU systems for its functioning. A user is free to use any of the architecture as per requirement. A system uses GPU if not mentioned explicitly. This process reduces memory usage to some extent. Due it this capacity Tensorflow is viewed as a hardware acceleration library.

6. Compatible
It is compatible with many programming languages like Python, C++, JavaScript, etc. This allows users to work in an environment they are comfortable in.

7. Architectural Support
The TensorFlow architecture uses TPU which makes computation faster than CPU and GPU. Models which are built over TPU can be easily deployed over clouds and works faster compared to the other two.

8. Library management
Being backed by google, Tensorflow is updated frequently and is capable of displaying outstanding performance.

Disadvantages

1. No windows support
Besides all the advantages possessed by Tensorflow, it has a very limited set of features for Windows users. For Linux users this isn’t the case there is a wide arcade of features when it comes to them.

2. Slow
It is comparatively slower and less usable compared to its competing frameworks.

3. GPU support
Tensorflow has only NVIDIA support for GPU and Python programming language support for GPU programming.

4. Frequent updates
Tensorflow undergoes frequent updates making it overhead for a user to time to time uninstall and reinstall it so that it can bind and be blended with its latest updates.

5. Architectural limitation
Tensorflow’s TPU architecture allows only execution of models and doesn’t allow its training.

6. Inconsistent
Tensorflow contains homonyms as names of its contents which makes it difficult for a user to remember and use. A single name is used for various different purposes and this is where the confusion starts.


#15. What do you know about supervised and unsupervised machine learning?

Supervised learning: Supervised learning, as the name indicates, has the presence of a supervisor as a teacher. Basically supervised learning is when we teach or train the machine using data that is well-labelled. Which means some data is already tagged with the correct answer. After that, the machine is provided with a new set of examples(data) so that the supervised learning algorithm analyses the training data(set of training examples) and produces a correct outcome from labeled data.

For instance, suppose you are given a basket filled with different kinds of fruits. Now the first step is to train the machine with all the different fruits one by one like this:

If the shape of the object is rounded and has a depression at the top, is red in color, then it will be labeled as –Apple.
If the shape of the object is a long curving cylinder having Green-Yellow color, then it will be labeled as –Banana.
Now suppose after training the data, you have given a new separate fruit, say Banana from the basket, and asked to identify it.
 Supervised learning is classified into two categories of algorithms:

Classification: A classification problem is when the output variable is a category, such as “Red” or “blue” , “disease” or “no disease”.
Regression: A regression problem is when the output variable is a real value, such as “dollars” or “weight”.
Types:-

Regression
Logistic Regression
Classification
Naive Bayes Classifiers
K-NN (k nearest neighbors)
Decision Trees
Support Vector Machine

Advantages:-
Supervised learning allows collecting data and produces data output from previous experiences.
Helps to optimize performance criteria with the help of experience.
Supervised machine learning helps to solve various types of real-world computation problems.
It performs classification and regression tasks.
It allows estimating or mapping the result to a new sample.
We have complete control over choosing the number of classes we want in the training data.
Disadvantages:-
Classifying big data can be challenging.
Training for supervised learning needs a lot of computation time. So, it requires a lot of time.
Supervised learning cannot handle all complex tasks in Machine Learning.
 Computation time is vast for supervised learning.
It requires a labelled data set.
 It requires a training process.
Unsupervised learning:
Unsupervised learning is the training of a machine using information that is neither classified nor labeled and allowing the algorithm to act on that information without guidance. Here the task of the machine is to group unsorted information according to similarities, patterns, and differences without any prior training of data.

Unlike supervised learning, no teacher is provided that means no training will be given to the machine. Therefore the machine is restricted to find the hidden structure in unlabeled data by itself.
For instance, suppose it is given an image having both dogs and cats which it has never seen.
Clustering: A clustering problem is where you want to discover the inherent groupings in the data, such as grouping customers by purchasing behavior.
Association: An association rule learning problem is where you want to discover rules that describe large portions of your data, such as people that buy X also tend to buy Y.
Types of Unsupervised Learning:-
K-means clustering
KNN (k-nearest neighbors)
Hierarchal clustering
Anomaly detection
Neural Networks
Principle Component Analysis
Independent Component Analysis
Apriori algorithm
Singular value decomposition